apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
  creationTimestamp: null
  generation: 1
  labels:
    app: debugging-tools
  name: debugging-tools
spec:
  # revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: debugging-tools
  template:
    metadata:
      labels:
        app: debugging-tools
    spec:
      # nodeName:    # `kubectl get node` to get a node
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: armory/debugging-tools:latest
        imagePullPolicy: Always
        name: debugging-tools
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
