apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: debugging-tools-sshd
  name: debugging-tools-sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: debugging-tools-sshd
  template:
    metadata:
      labels:
        name: debugging-tools-sshd
    spec:
      containers:
      - image: armory/debugging-tools-sshd:latest
        imagePullPolicy: Always
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        name: sshd
        volumeMounts:
        - name: ssh-key
          mountPath: /root/.ssh
      volumes:
      - name: ssh-key
        configMap:
          name: ssh-key
          defaultMode: 0600
